spring:
  application:
    name: grade-management-system
  datasource:
    url: jdbc:mysql://db:3306/grade_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  profiles:
    active: dev

server:
  port: 8080

cors:
  allowed-origins: ""
